FROM amazon/aws-lambda-python:3.8

RUN yum update -y && yum install -y git && yum clean all

COPY ./app ./app
COPY ./requirements.txt ./requirements.txt
RUN pip install -r ./requirements.txt

CMD ["app.main.handler"]